### ISSUE TITLE
Tip: Zlepšení componenty

### ISSUE THREAD

**Issue by tomasvn** [Helenadost/FAQ-Dropdown#1]
Ahoj, @Helenadost  u takových interaktivní prvků je lepší použít nativní věci jako jsou `buttony` místo `div` elementu, který zde používáš. Button element ti zařídí různé věci - defaultní focus, interaktivita přes enter a spacebar, kvůli přístupnosti. Příklad zde https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/

**Comment by Helenadost** [comment]
Ahoj @tomasvn, díky za komentář. Upravila jsem a pro příště na to budu myslet :)
